translation_dict = {
    "hello": "hei",
    "bye" : "ddyl",
    "and": "ha", # there's also hag
    "welcome": "croma",
    "early": "rulna",
    "middle": "llad",
    "late": "mear",
    "dark": "mezh",
    "day": "ddawr",
    "morning": "dulna",
    "afternoon": "daidd",
    "evening": "dear",
    "night": "dezh",
    "one": "un",
    "two": "tro",
    "three": "tri",
    "four": "môr",
    "five": "fid",
    "six": "sawll",
    "seven": "zefen",
    "eight": "aizh",
    "nine": "vur",
    "ten": "enda",
    "walk" : "ywar",
    "walked" : "yawrdd",
    "run" : "wadhar",
    "ran" : "wadhardd",
    "we" : "er",
    "us" : "er",
    "me" : "de",
    "i" : "de",
    "im" : "d'im",
    "my" : "ae",
    "in" : "o",
    "I am" : "de imev",
    "good" : "dañv",
    "bad" : "dwr",
    "yes" : "enno",
    "no" : "nage",
    "america" : "Amerika",
    "wales" : "Kembrau",
    "brittany" : "Breizh",
    "ireland" : "Iwerzhon",
    "scotland" : "Albann",
    "language" : "yaith",
    "going" : "nezhen",
    "make" : "kyn",
    "has" : "ddynin",
    "had" : "ddynin",
    "feeling" : "mynnoifo",
    "linguistic" : "vreynnod",
    "linguistics" : "vreynnoden",
    "word" : "kannin",
    "words" : "kannyn",
    "languages" : "yaithyn",
    "boy" : "kromgen",
    "girl" : "dwirar",
    "man" : "den",
    "woman" : "llynar",
    "love" : "bwydda",
    "friend" : "caraidd",
    "lover" : "bwyddawr",
    "mother" : "mamañ",
    "father" : "drouañ",
    "brother" : "merdañ",
    "sister" : "merfañ",
    "family" : "frazken",
    "nantes" : "Naoned",
    "Quimper" : "Kemper",
    "france" : "Frañz",
    "gaul" : "Gaulwez",
    "spain" : "Espanya",
    "germany" : "Almañ",
    "italy" : "Romez",
    "poland" : "Polañd",
    "russia" : "Raos",
    "england" : "Bro-Saez",
    "turkey" : "Gwaelya",
    "go" : "nyder",
    "to" : "eo",
    "please" : "myrdd",
    "happy" : "dyrdd",
    "sad" : "bwyrn",
    "angry" : "plañv",
    "fear" : "vawrzh",
    "tired" : "vrendan",
    "hate" : "plañvern",
    "small" : "gen",
    "big" : "krañv",
    "sleep" : "vrenenn",
    "awake" : "kynenn",
    "nation" : "glyn",
    "water" : "dyzh",
    "fire" : "danau",
    "hot" : "byn",
    "same" : "grez",
    "probably" : "acyn",
    "will" : "yozh",
    "soon" : "rulyd",
    "cold" : "arddyn",
    "warm" : "byn",
    "sun" : "deol",
    "moon" : "meddyn",
    "light" : "mynyth",
    "moving" : "drañ",
    "air" : "mydd",
    "wind" : "myddrañ",
    "speak" : "nelau",
    "truth" : "dañlau",
    "lie" : "dwrlau",
    "fast" : "arned",
    "slow" : "vormarn",
    "earth" : "tarrien",
    "ground" : "tarrien",
    "star" : "senou",
    "tree" : "kerdien",
    "you" : "arn",
    "he" : "eñv",
    "him" : "eñv",
    "she" : "eñvar",
    "her" : "eñvar",
    "his" : "meñvawr",
    "hers" : "eñvawr",
    "glen" : "glwn",
    "glens" : "glwnyn",
    "land" : "gwlad",
    "nation" : "gwlad",
    "nations" : "gwladyn",
    "lands" : "gwladyn",
    "south" : "deau",
    "north" : "goglezh",
    "west" : "kornrog",
    "east" : "reter",
    "mountain" : "menezh",
    "mountains" : "menezhyn",
    "arree" : "Are",
    "of" : "a", # also ag
    "the" : "y'r",
    "thanks" : "ddynam",
    "battle" : "emgann",
    "fight" : "stoerm",
    "I go" : "zenn",
    "to the" : "myr",
    "john" : "Yann",
    "johnathan" : "Yann",
    "david" : "Dafyd",
    "fennonkeddanenn" : "slogan",
    "fennonkeddanennyn" : "slogans",
    "went" : "dos",
    "really" : "kwenn", 
    "chat" : "yevh",
    "talk" : "yevh",
    "country" : "gwlad",
    "traverser" : "nutzh",
    "sailor" : "dyzh-nutzh",
    "sailors" : "dyzh-nutzh",
    "arthur" : "Arzhur",
    "why" : "enn",
    "stuff" : "vann",
    "are" : "arv",
    "how" : "an",
    "maki" : "Honsk",
    "andrew" : "Anndra",
    "idiot" : "pek",
    "thought" : "prwn",
    "dumb" : "pec",
    "stupid" : "pec",
    "bed" : "glasek",
    "driven" : "dan",
    "dragon" : "draig",
    "with" : "azhen",
    "called" : "vrenn",
    "do" : " mae",
    "know" : "llemen",
    "into" : "naen",
    "is" : "kan",
    "government" : "gwladgan",
    "it" : "rhyn",
    "lord" : "Aoutrou",
    "god" : "Dwy",
    "holy" : "dym",
    "Jesus" : "Yesys",
    "home" : "tynn",
    "house" : "trann",
    "heaven" : "Dym-Tynn",
    "now" : "ddwn",
    "syrup" : "demgennyed",
    "caffeine" : "kyngennyed",
    "people" : "enn",
    "place" : "gwazh",
    "everyone" : "onn-enn",
    "that" : "nev",
    "drink" : "ffen",
    "dont" : "dynn",
    "eat" : "trenn",
    "like" : "yennar",
    "love" : "yeskar",
    "nothing" : "nann-gwazh",
    "but" : "ken",
    "what" : "crym",
    "makes" : "bonn",
    "sure" : "yaonn",
    "no one" : "nann-enn",
    "everywhere" : "onn-gwazh",
    "traitor" : "dreitour",
    "nevan" : "what is",
    "worry" : "mekann",
    "worries" : "mekannyn",
    "dialect" : "mynnoddeniath",
    "dialects" : "mynnoddeniathyn",
    "Welsh dialect" : "mynnodd-Cymron",
    "Breton dialect" : "mynnodd-Brezhon",
    "Irish dialect" : "mynnodd-Irenon",
    "French dialect" : "mynnodd-Franon",
    "Spanish dialect" : "mynnodd-Spaynon",
    "Basque dialect" : "mynnodd-Bascnon",
    "honor" : "anour",
    "breton" : "Brezhon", # Brezhoned if the language
    "welsh" : "Cymron", # Cymroned if the language
    "english" : "Sacnon", # Saconed if the language
    "french" : "Franon", # Franoned if the language
    "spanish" : "Spaynon", # Spaynoned if the language
    "basque" : "Bascnon", #  Basconed if the language, Gwlad-Basc if the nation itself
    "Irish" : "Irenon" # Irenoned if the language
    "fucking" "merdear",
    "was" : "aekeo",
    "kinda" : "ta'moz",
    "sorta" : "ta'moz",
    "mean" : "rec'h",
    "head" : "penn",
    "heads" : "pennyn",
    "arm" : "ec'hon",
    "arms" : "ec'honyn",
    "leg" : "cor",
    "legs" : "coryn",
    "stomach" : "zor",
    "stomachs" : "zoryn",
    "heart" : "galon",
    "blood" : "gwad",
    "bleeding" : "gwaden",
    "room" : "karn",
    "bed" : "gwasker",
    "rest" : "kyner",
    "food" : "beaou",
    "waste" : "retouz",
    "bedroom" : "karn-gwasker",
    "living room" : "karn-cyner",
    "kitchen" : "karn-beaou",
    "bathroom" : "karn-retouz",
    "their" : "ker",
    "they" : "ker",
    "break" : "c'hanar",
    "breaking" : "c'hanerozh",
    "broke" : "c'hanarien",
    "have" : "ennoù",
    "just" : "ekrenn",
    "got" : "arvan",
    "news" : "nevau",
    "caught" : "karvenndou",
    "again" : "re-touz",
    "joking" : "nervan",
    "rainbow" : "kaneveden",
    # "break their" : "chan'ker"
    "your" : "aner",
    "hundred" : "kant",
    "thousand" : "drann",
    "mad" : "plañv",
    "gathered" : "konnarvet",
    "at" : "eñt",
    "pointe-du-raz" : "Pont-a-pler",
    "great" : "kra-zo",
    "fame" : "men-arou",
    "notoriety" : "men-arou",
    "raise" : "ero-kamm",
    "new" : "nevrezh",
    "old" : "hoz",
    "better" : "anker",
    "shame" : "kennerou",
    "red" : "ruzh",
    "blue" : "gwaz",
    "black" : "der",
    "white" : "gwenn",
    "green" : "gwer",
    "not" : "nann",
    "even" : "kau",
    "being" : "emger",
    "put" : "aker",
    "on" : "bret",
    "released" : "yennoukant",
    "list" : "aemovenn",
    "offender" : "gwedden",
    "if" : "chen",
    "fuck" : "merdean",
    "confessed" : "plijan",
    "admitted" : "plijan",
    "first" : "unan",
    "second" : "tronan",
    "third" : "trinan",
    "getting" : "avrekonn",
    "vocabulary" : "arc'hennoner",
    "hungry" : "rac'h",
    "dust" : "droust",
    "smoke" : "mogen",
    "horse" : "kazeg",
    "city" : "kaer",
    "town" : "kaer-genn",
    "royalty" : "vreic'hizier",
    "bourgeois" : "vreic'hizier",
    "Rennes" : "Raozhen",
    "Plogoff" : "Plogo",
    "summer" : "hañv",
    "winter" : "iverñ",
    "sky" : "nev",
    "nice" : "neiz",
    "drug" : "Kaffen",
    "drugs" : "kaffenyn"
}

def translate_word(word):
    # Separate punctuation from the word
    word_without_punctuation = word.rstrip('.,!?;:')
    punctuation = word[len(word_without_punctuation):]

    # Check if the word is in the dictionary
    if word_without_punctuation.lower() in translation_dict:
        # Translate the word and add back the punctuation
        translated_word = translation_dict[word_without_punctuation.lower()] + punctuation
        return translated_word
    else:
        return word  # Return the original word if translation not found

def translate_sentence(sentence):
    # Split the input sentence into words
    words = sentence.split()

    # Translate each word and store the translations in a list
    translated_words = [translate_word(word) for word in words]

    # Join the translated words to form the translated sentence
    translated_sentence = ' '.join(translated_words)

    return translated_sentence

while True:
    # Input sentence to translate
    sentence_to_translate = input("Enter a sentence to translate (type '!done' to exit): ")

    if sentence_to_translate.lower() == '!done':
        print("Exiting the program. Goodbye!")
        break

    # Translate and print the result
    translation = translate_sentence(sentence_to_translate)
    print(f"Translation: {translation}")